version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      rust-dependencies:
        patterns: ["*"]
    ignore:
      - dependency-name: tree-sitter
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
      - dependency-name: tree-sitter-bash
        update-types:
          - version-update:semver-major
          - version-update:semver-minor

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      actions-dependencies:
        patterns: ["*"]
